ALTER TABLE itens_notas_fiscais 
ADD COLUMN ncm VARCHAR(8) NOT NULL DEFAULT '00000000',
ADD COLUMN cfop VARCHAR(4) NOT NULL DEFAULT '5102',
ADD COLUMN cst_icms VARCHAR(3) NOT NULL DEFAULT '000',
ADD COLUMN base_calculo_icms DECIMAL(19, 2) DEFAULT 0.00,
ADD COLUMN aliquota_icms DECIMAL(5, 2) DEFAULT 0.00,
ADD COLUMN valor_icms DECIMAL(19, 2) DEFAULT 0.00;

ALTER TABLE notas_fiscais 
ADD COLUMN total_icms DECIMAL(19, 2) DEFAULT 0.00;